
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Nov 21 08:05:31 CST 2011
//----------------------------------------------------

package proyectocompiladores2r;

/** CUP generated class containing symbol constants. */
public class SymbolosProyecto {
  /* terminals */
  public static final int PUBLICO = 5;
  public static final int CHAR = 53;
  public static final int POR = 32;
  public static final int MENORQ = 36;
  public static final int ENTERO = 49;
  public static final int CASE = 14;
  public static final int PC = 21;
  public static final int INT = 52;
  public static final int PA = 20;
  public static final int FOR = 11;
  public static final int NOIGUAL = 40;
  public static final int NOT = 43;
  public static final int AND = 41;
  public static final int MENORIGUAL = 38;
  public static final int PRIVADO = 7;
  public static final int IGUAL = 39;
  public static final int CARACTER = 51;
  public static final int OR = 42;
  public static final int BOOL = 54;
  public static final int CLASS = 3;
  public static final int DIV = 33;
  public static final int ASIGNA = 44;
  public static final int CC = 23;
  public static final int IF = 9;
  public static final int THIS = 8;
  public static final int CA = 22;
  public static final int ID = 48;
  public static final int MAYORIGUAL = 37;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int TRUE = 46;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int CADENA = 50;
  public static final int MENOS = 31;
  public static final int MOD = 34;
  public static final int BREAK = 15;
  public static final int VOID = 58;
  public static final int PCOMA = 25;
  public static final int SWITCH = 13;
  public static final int IMPORT = 2;
  public static final int LLC = 19;
  public static final int LLA = 18;
  public static final int ELSE = 10;
  public static final int PUNTO = 28;
  public static final int MAYORQ = 35;
  public static final int WHILE = 12;
  public static final int DEFAULT = 16;
  public static final int FLOAT = 57;
  public static final int EXTENDS = 4;
  public static final int DPUNTOS = 26;
  public static final int PROTEGIDO = 6;
  public static final int STRING = 56;
  public static final int FALSE = 47;
  public static final int AP = 29;
  public static final int VAR = 55;
  public static final int DO = 17;
  public static final int MAS = 30;
}

