
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Nov 21 08:18:02 CST 2011
//----------------------------------------------------

package proyectocompiladores2r;

/** CUP generated class containing symbol constants. */
public class Symbolos3D {
  /* terminals */
  public static final int POR = 13;
  public static final int MENORQ = 22;
  public static final int ENTERO = 9;
  public static final int PUSH = 5;
  public static final int PC = 34;
  public static final int INT = 36;
  public static final int PA = 33;
  public static final int NOIGUAL = 26;
  public static final int MENORIGUAL = 23;
  public static final int IGUAL = 25;
  public static final int CARACTER = 10;
  public static final int CALL = 4;
  public static final int DIV = 14;
  public static final int ASIGNA = 28;
  public static final int CC = 30;
  public static final int IF = 2;
  public static final int CA = 29;
  public static final int ID = 8;
  public static final int MAYORIGUAL = 24;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int HEAP = 7;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MENOS = 12;
  public static final int STACK = 6;
  public static final int MOD = 15;
  public static final int VOID = 16;
  public static final int PCOMA = 32;
  public static final int LLC = 20;
  public static final int LLA = 19;
  public static final int PUNTO = 18;
  public static final int MAYORQ = 21;
  public static final int GOTO = 3;
  public static final int FLOAT = 37;
  public static final int DPUNTOS = 31;
  public static final int LABEL = 17;
  public static final int MAS = 11;
}

